version: '3.10'

services:
  mlflow:
    image: mlflow:latest
    environment:
      - MLFLOW_TRACKING_URI=http://localhost:5000
    ports:
      - "5000:5000"
    volumes:
      - ./mlruns:/mlflow/mlruns
    command: mlflow server --backend-store-uri sqlite:///mlflow.db --default-artifact-root /mlflow/mlruns --host 0.0.0.0 --port 5000
